import type { Metadata } from "next";
import "../styles/style.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: "400",
	variable: "--font-montserrat",
});

export const metadata: Metadata = {
	title: "Tomiwa Adelae",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
